apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: jenkinsx-8888-gke
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    gke:
      projectNumber: "379361290101"
    kanikoFlags: --skip-unused-stages --snapshotMode=redo
    project: jenkinsx-8888
    provider: gke
    registry: gcr.io
    zone: us-central1
  environments:
  - key: dev
    owner: skeeterx-ch
    repository: Cluster
  - key: staging
  - key: production
  ingress:
    domain: cluster.verissimo.net.br
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: skeeterx-ch
  repository: nexus
  secretStorage: gsm
  vault: {}
  webhook: lighthouse
