# Source: jx-kh-check/templates/jx-pod-status-check.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jx-pod-status-role
  annotations:
    meta.helm.sh/release-name: 'health-checks-install'
  labels:
    gitops.jenkins-x.io/pipeline: 'cluster'
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
    verbs:
      - get
      - list
      - watch
