# Source: jx-kh-check/templates/jx-secrets-check.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jx-secrets-role
  annotations:
    meta.helm.sh/release-name: 'health-checks-install'
  labels:
    gitops.jenkins-x.io/pipeline: 'cluster'
rules:
  - apiGroups:
      - "kubernetes-client.io"
    resources:
      - externalsecrets
    verbs:
      - get
      - list
      - watch
