# Source: jx-kh-check/templates/jx-secrets-check.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jx-secrets-sa
  namespace: jx
  annotations:
    meta.helm.sh/release-name: 'health-checks-install'
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
